### ISSUE TITLE
iOS 9.3 Hosted Fields non responsive fields on iOS

### ISSUE THREAD

**Issue by NickMele** [braintree/braintree-web#207]
In iOS 9.3 on an iPhone 5s, I am experiencing issues where the user selects a field in hosted fields and they are unable to type. The keyboard is open and the cursor blinks just like any other field, but as you tap keys nothing appears. You have to close the keyboard and then tap the field again to be able to type.

Sometimes it happens if you tap a field twice and the keyboard appears you are unable to type.

We are using v3.0.2.

**Comment by crookedneighbor** [comment]
I can't reproduce this in Safari on iOS 9.3.5 on an iPhone 6.

Here's a simple jsfiddle: https://jsfiddle.net/hh36u1t1/2/

Could you try going there and seeing if you get the same behavior? If you can't reproduce it there, can you provide some sample code that can reproduce it?

**Comment by NickMele** [comment]
So i can't reproduce it in the fiddle that you created. But we are using this in a ionic/cordova app and I created a blank ionic/cordova app with this code in it and I was able to reproduce it running this within the simulator.

I am thinking that it has something to do with it running within the WebView

**Comment by crookedneighbor** [comment]
I've just tested it in both a UI webview and a WK webview and could not reproduce the issue you describe. It may be because you are using ionic/cordova, which we do not officially support.

From [our documentation](http://braintree.github.io/braintree-web/current/#browser-support-mobile): 

>`braintree.js` is neither tested nor developed for hybrid runtimes such as Cordova, PhoneGap, Ionic, React Native, and Electron. While some success may be had in such environments, our SDK is optimized for the browser and its security policies and may not function correctly outside of them.

**Comment by crookedneighbor** [comment]
I'm going to close this now, but if you can provide a reproducible example outside of ionic/cordova, definitely re-open the issue and send it along.

**Comment by NickMele** [comment]
Thanks @crookedneighbor. I understand, and if i am able to get something put together that reproduces the issue I will for sure re-open.

I don't want to keep pushing it, but do you have any hint of what is happening here? Is it for sure the WebView that is causing the issue? If not no worries, just wanted to see if you maybe had an idea of what was going on even though you guys don't support it.

**Comment by crookedneighbor** [comment]
From my testing, it's probably not the webview. I was unable to reproduce the error in a webview. If the problem _is_ a webview, that's a problem for us since we _do_ support webviews for Hosted Fields. 

If you can create a sample ionic app that can reproduce the problem, I'm happy to spend a few minutes looking at it to see if there's anything obvious about it.

**Comment by NickMele** [comment]
Hi @crookedneighbor,

I have created a super bare bones cordova app with the minimum dependencies needed to get hosted fields working and I am still able to reproduce the issue. I know you said that you don't support Cordova, but if we are unable to resolve this issue we are going to be forced to switch from hosted fields. We would like to avoid this for now.

**You should be able to quickly run the example:**
1. Clone repo `https://github.com/NickMele/hosted-fields-test`
2. Install cordova if you don't have it already `sudo npm install -g cordova`
3. Navigate to cloned repo
4. Run `npm run start` to install the platforms/plugins needed and run the app in the simulator

The sample contains a generic iframe that loads in an html input where you can see the issue does not occur. Below that is a hosted fields instance in which the issue does occur by doing the following:
1. Tap on a field to bring up the keyboard/cursor.
2. Notice that you can type in the field
3. Tap in the field again while your cursor is still in there and notice it looks like you should be able to type, however you cannot.
4. It gets even weirder when you tap the input again and sometimes it seems like your cursor will jump to the middle of the screen. Not sure if this is an indication of the problem or not.

I really would appreciate it if you could take a look at this, if not I understand.

Thanks

**Comment by crookedneighbor** [comment]
I've tracked down why this is happening. 🤞 it'll go out in the next release.

**Comment by NickMele** [comment]
Nice! That is awesome news. I was getting pretty worried. Thank you so much for taking the time to look into it.

**Comment by lilaconlee** [comment]
We've released [3.16.0](https://github.com/braintree/braintree-web/blob/master/CHANGELOG.md#3160) with the fix. Thanks for reporting the bug and let us know if this doesn't fix your issue!

**Comment by NickMele** [comment]
Thanks for attempting to fix the issue, however we are still able to reproduce the issue running both version 3.16.0 and 3.17.0.

**Comment by crookedneighbor** [comment]
@NickMele Have you tried running the app on an actual device? Sometimes there are differences of behavior between a simulator and a real device.

**Comment by NickMele** [comment]
Yep, we had it deployed in our staging environment and our QA caught it on multiple actual devices (iPhone 6, iPhone 5c, iPhone 6s) that it was still occurring.

**Comment by crookedneighbor** [comment]
Hmmm.... I just re-tried it on the sample app you provided. 

Using 3.14.0, I got the issue. 

Using 3.17.0, I did not. It was resolved.

Can you reproduce on the sample app if you upgrade the version to 3.17.0?

**Comment by migburillo** [comment]
Hello @NickMele @crookedneighbor, 
I'm facing the same issue, using Ionic and your js library 3.18.0 

When I tap on inputs they get a strange dark grey overlay and then lose focus automatically, so you can't write in.
But.... in very few cases the prompt remains in the input and you can write normally

Hope I bring more clues for fixing this...

I'm going to try wkwebview rendering engine meanwhile

Thanks guys

**Comment by crookedneighbor** [comment]
@migburillo Happy to help if you can provide a reproducible example. Like I said previously, with the example app I was given, I could reproduce with the old version, but not the current version.

**Comment by gongiskhan** [comment]
Just in case someone is still having the same issue. For me it solved it by applying this fix: https://stackoverflow.com/questions/36234957/internal-navigation-rejected-allow-navigation-not-set-in-cordova-on-ios

Now I can focus on and edit hosted fields on iOS without issues, including the keyboard getting launched.
